### ISSUE TITLE
colors.cmaps does not validate cleanly

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psy-simple#27]
#### Code Sample, a copy-pastable example if possible

```bash
cat >> ~/.config/psyplot/psyplotrc.yml << EOF

colors.cmaps: 
  rgb: ['r', 'g', 'b']

EOF
```
#### Problem description

the `validate_cmaps` does not validate cleanly, you get `Trying to set 'colors.cmaps' to {'rgb': ['r', 'g', 'b']} via the update method of RcParams which does not validate cleanly.`

see also https://github.com/psyplot/psyplot-gui/issues/25

#### Output of ``psyplot -aV``

<details>

<summary>psyplot -aV</summary>

```
psy_maps.plugin:
  requirements:
    cartopy: 0.18.0
  version: 1.3.2+2.g26b6411
psy_reg.plugin:
  requirements:
    scipy: 1.5.3
    statsmodels: 0.12.1
  version: 1.3.0+3.gc849e50
psy_simple.plugin:
  version: 1.3.1
psy_strat.plugin:
  version: 0.1.0
psy_transect.plugin:
  version: 0.0.1.dev0
psyplot:
  requirements:
    matplotlib: 3.3.3
    numpy: 1.19.4
    pandas: 1.1.4
    python: 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05)  [GCC
      7.5.0]
    xarray: 0.16.2
  version: 1.3.1+3.g84dcb3d.dirty
psyplot_gui:
  requirements:
    pyqt: 5.12.3
    qt: 5.12.9
    qtconsole: 5.0.1
  version: 1.3.0
```

</details>
